"""initial schema

Revision ID: 5c4582ffcd85
Revises: 
Create Date: 2026-08-16 14:53:01.469073

"""
from typing import Sequence, Union

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5c4582ffcd85'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector prerequisite for the `embedding` vector column — an environmental
    # dependency that cannot be expressed in the SQLAlchemy model, so it is not
    # emitted by --autogenerate and must be declared here.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('memory_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('namespace', sa.String(), nullable=True),
    sa.Column('memory_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_session_id', sa.String(), nullable=True),
    sa.Column('source_turn_start', sa.Integer(), nullable=False),
    sa.Column('source_turn_end', sa.Integer(), nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('reinforcement_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('supersedes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('superseded_by', sa.String(), nullable=False),
    sa.Column('embedding', Vector(1024), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('last_accessed_at', sa.String(), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(content,''))", persisted=True), nullable=True),
    sa.PrimaryKeyConstraint('memory_id')
    )
    op.create_index('idx_memories_content_tsv', 'memories', ['content_tsv'], unique=False, postgresql_using='gin')
    op.create_index('idx_memories_embedding', 'memories', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_memories_namespace_status', 'memories', ['namespace', 'status'], unique=False)
    op.create_index('idx_memories_namespace_type', 'memories', ['namespace', 'memory_type'], unique=False)
    op.create_index('idx_memories_user', 'memories', ['user_id'], unique=False)
    op.create_index('idx_memories_user_namespace', 'memories', ['user_id', 'namespace'], unique=False)
    op.create_index('ix_memories_namespace_pattern', 'memories', ['namespace'], unique=False, postgresql_ops={'namespace': 'text_pattern_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memories_namespace_pattern', table_name='memories', postgresql_ops={'namespace': 'text_pattern_ops'})
    op.drop_index('idx_memories_user_namespace', table_name='memories')
    op.drop_index('idx_memories_user', table_name='memories')
    op.drop_index('idx_memories_namespace_type', table_name='memories')
    op.drop_index('idx_memories_namespace_status', table_name='memories')
    op.drop_index('idx_memories_embedding', table_name='memories', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('idx_memories_content_tsv', table_name='memories', postgresql_using='gin')
    op.drop_table('memories')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
